
Country = (
('none' 'Select Country'),
('Afghanistan'),
('Albania'),
('Algeria'),
('American Samoa'),
('Angola'),
('Anguilla'),
('Antartica'),
('Antigua and Barbuda'),
('Argentina'),
('Armenia'),
('Aruba'),
('Ashmore and Cartier Island'),
('Australia'),
('Austria'),
('Azerbaijan'),
('Bahamas'),
('Bahrain'),
('Bangladesh'),
('Barbados'),
('Belarus'),
('Belgium'),
('Belize'),
('Benin'),
('Bermuda'),
('Bhutan'),
('Bolivia'),
('Bosnia and Herzegovina'),
('Botswana'),
('Brazil'),
('British Virgin Islands'),
('Brunei'),
('Bulgaria'),
('Burkina Faso'),
('Burma'),
('Burundi'),
('Cambodia'),
('Cameroon'),
('Canada'),
('Cape Verde'),
('Cayman Islands'),
('Central African Republic'),
('Chad'),
('Chile'),
('China'),
('Christmas Island'),
('Clipperton Island'),
('Cocos (Keeling), Islands'),
('Colombia'),
('Comoros'),
('Congo, Democratic Republic of the'),
('Congo, Republic of the'),
('Cook Islands'),
('Costa Rica'),
('Cote dIvoire'),
('Croatia'),
('Cuba'),
('Cyprus'),
('Czeck Republic'),
('Denmark'),
('Djibouti'),
('Dominica'),
('Dominican Republic'),
('Ecuador'),
('Egypt'),
('El Salvador'),
('Equatorial Guinea'),
('Eritrea'),
('Estonia'),
('Ethiopia'),
('Europa Island'),
('Falkland Islands (Islas Malvinas),'),
('Faroe Islands'),
('Fiji'),
('Finland'),
('France'),
('French Guiana'),
('French Polynesia'),
('French Southern and Antarctic Lands'),
('Gabon'),
('Gambia, The'),
('Gaza Strip'),
('Georgia'),
('Germany'),
('Ghana'),
('Gibraltar'),
('Glorioso Islands'),
('Greece'),
('Greenland'),
('Grenada'),
('Guadeloupe'),
('Guam'),
('Guatemala'),
('Guernsey'),
('Guinea'),
('Guinea-Bissau'),
('Guyana'),
('Haiti'),
('Heard Island and McDonald Islands'),
('Holy See (Vatican City),'),
('Honduras'),
('Hong Kong'),
('Howland Island'),
('Hungary'),
('Iceland'),
('India'),
('Indonesia'),
('Iran'),
('Iraq'),
('Ireland'),
('Ireland, Northern'),
('Israel'),
('Italy'),
('Jamaica'),
('Jan Mayen'),
('Japan'),
('Jarvis Island'),
('Jersey'),
('Johnston Atoll'),
('Jordan'),
('Juan de Nova Island'),
('Kazakhstan'),
('Kenya'),
('Kiribati'),
('Korea, North'),
('Korea, South'),
('Kuwait'),
('Kyrgyzstan'),
('Laos'),
('Latvia'),
('Lebanon'),
('Lesotho'),
('Liberia'),
('Libya'),
('Liechtenstein'),
('Lithuania'),
('Luxembourg'),
('Macau'),
('Macedonia, Former Yugoslav Republic of'),
('Madagascar'),
('Malawi'),
('Malaysia'),
('Maldives'),
('Mali'),
('Malta'),
('Man, Isle of'),
('Marshall Islands'),
('Martinique'),
('Mauritania'),
('Mauritius'),
('Mayotte'),
('Mexico'),
('Micronesia, Federated States of'),
('Midway Islands'),
('Moldova'),
('Monaco'),
('Mongolia'),
('Montserrat'),
('Morocco'),
('Mozambique'),
('Namibia'),
('Nauru'),
('Nepal'),
('Netherlands'),
('Netherlands Antilles'),
('New Caledonia'),
('New Zealand'),
('Nicaragua'),
('Niger'),
('Nigeria'),
('Niue'),
('Norfolk Island'),
('Northern Mariana Islands'),
('Norway'),
('Oman'),
('Pakistan'),
('Palau'),
('Panama'),
('Papua New Guinea'),
('Paraguay'),
('Peru'),
('Philippines'),
('Pitcaim Islands'),
('Poland'),
('Portugal'),
('Puerto Rico'),
('Qatar'),
('Reunion'),
('Romainia'),
('Russia'),
('Rwanda'),
('Saint Helena'),
('Saint Kitts and Nevis'),
('Saint Lucia'),
('Saint Pierre and Miquelon'),
('Saint Vincent and the Grenadines'),
('Samoa'),
('San Marino'),
('Sao Tome and Principe'),
('Saudi Arabia'),
('Scotland'),
('Senegal'),
('Seychelles'),
('Sierra Leone'),
('Singapore'),
('Slovakia'),
('Slovenia'),
('Solomon Islands'),
('Somalia'),
('South Africa'),
('South Georgia and South Sandwich Islands'),
('Spain'),
('Spratly Islands'),
('Sri Lanka'),
('Sudan'),
('Suriname'),
('Svalbard'),
('Swaziland'),
('Sweden'),
('Switzerland'),
('Syria'),
('Taiwan'),
('Tajikistan'),
('Tanzania'),
('Thailand'),
('Tobago'),
('Toga'),
('Tokelau'),
('Tonga'),
('Trinidad'),
('Tunisia'),
('Turkey'),
('Turkmenistan'),
('Tuvalu'),
('Uganda'),
('Ukraine'),
('United Arab Emirates'),
('United Kingdom'),
('Uruguay'),
('USA'),
('Uzbekistan'),
('Vanuatu'),
('Venezuela'),
('Vietnam'),
('Virgin Islands'),
('Wales'),
('Wallis and Futuna'),
('West Bank'),
('Western Sahara'),
('Yemen'),
('Yugoslavia'),
('Zambia'),
('Zimbabwe'),
)






Currency = (
('USD', 'America United States Dollars – USD'),
("AFN", "Afghanistan Afghanis – AFN"),
("ALL", "Albania Leke – ALL"),
("DZD", "Algeria Dinars – DZD"),
("ARS", "Argentina Pesos – ARS"),
("AUD", "Australia Dollars – AUD"),
("ATS", "Austria Schillings – ATS"),
("BSD", "Bahamas Dollars – BSD"),
("BHD", "Bahrain Dinars – BHD"),
("BDT", "Bangladesh Taka – BDT"),
("BBD", "Barbados Dollars – BBD"),
("BEF", "Belgium Francs – BEF"),
("BMD", "Bermuda Dollars – BMD"),
 
("BRL", "Brazil Reais – BRL"),
("BGN", "Bulgaria Leva – BGN"),
("CAD", "Canada Dollars – CAD"),
("XOF", "CFA BCEAO Francs – XOF"),
("XAF", "CFA BEAC Francs – XAF"),
("CLP", "Chile Pesos – CLP"),
 
("CNY", "China Yuan Renminbi – CNY"),
("CNY", "RMB (China Yuan Renminbi), – CNY"),
("COP", "Colombia Pesos – COP"),
("XPF", "CFP Francs – XPF"),
("CRC", "Costa Rica Colones – CRC"),
("HRK", "Croatia Kuna – HRK"),
 
("CYP", "Cyprus Pounds – CYP"),
("CZK", "Czech Republic Koruny – CZK"),
("DKK", "Denmark Kroner – DKK"),
("DEM", "Deutsche (Germany), Marks – DEM"),
("DOP", "Dominican Republic Pesos – DOP"),
("NLG", "Dutch (Netherlands), Guilders – NLG"),
 
("XCD", "Eastern Caribbean Dollars – XCD"),
("EGP", "Egypt Pounds – EGP"),
("EEK", "Estonia Krooni – EEK"),
("EUR", "Euro – EUR"),
("FJD", "Fiji Dollars – FJD"),
("FIM", "Finland Markkaa – FIM"),
 
("FRF", "France Francs – FRF"),
("DEM", "Germany Deutsche Marks – DEM"),
("XAU", "Gold Ounces – XAU"),
("GRD", "Greece Drachmae – GRD"),
("GTQ", "Guatemalan Quetzal – GTQ"),
("NLG", "Holland (Netherlands), Guilders – NLG"),
("HKD", "Hong Kong Dollars – HKD"),
 
("HUF", "Hungary Forint – HUF"),
("ISK", "Iceland Kronur – ISK"),
("XDR", "IMF Special Drawing Right – XDR"),
("INR", "India Rupees – INR"),
("IDR", "Indonesia Rupiahs – IDR"),
("IRR", "Iran Rials – IRR"),
 
("IQD", "Iraq Dinars – IQD"),
("IEP", "Ireland Pounds – IEP"),
("ILS", "Israel New Shekels – ILS"),
("ITL", "Italy Lire – ITL"),
("JMD", "Jamaica Dollars – JMD"),
("JPY", "Japan Yen – JPY"),
 
("JOD", "Jordan Dinars – JOD"),
("KES", "Kenya Shillings – KES"),
("KRW", "Korea (South), Won – KRW"),
("KWD", "Kuwait Dinars – KWD"),
("LBP", "Lebanon Pounds – LBP"),
("LUF", "Luxembourg Francs – LUF"),
 
("MYR", "Malaysia Ringgits – MYR"),
("MTL", "Malta Liri – MTL"),
("MUR", "Mauritius Rupees – MUR"),
("MXN", "Mexico Pesos – MXN"),
("MAD", "Morocco Dirhams – MAD"),
("NLG", "Netherlands Guilders – NLG"),
 
("NZD", "New Zealand Dollars – NZD"),
("NGN", "Nigeria Naira – NGN"),
("NOK", "Norway Kroner – NOK"),
("OMR", "Oman Rials – OMR"),
("PKR", "Pakistan Rupees – PKR"),
("XPD", "Palladium Ounces – XPD"),
("PEN", "Peru Nuevos Soles – PEN"),
 
("PHP", "Philippines Pesos – PHP"),
("XPT", "Platinum Ounces – XPT"),
("PLN", "Poland Zlotych – PLN"),
("PTE", "Portugal Escudos – PTE"),
("QAR", "Qatar Riyals – QAR"),
("RON", "Romania New Lei – RON"),
 
("ROL", "Romania Lei – ROL"),
("RUB", "Russia Rubles – RUB"),
("SAR", "Saudi Arabia Riyals – SAR"),
("XAG", "Silver Ounces – XAG"),
("SGD", "Singapore Dollars – SGD"),
("SKK", "Slovakia Koruny – SKK"),
 
("SIT", "Slovenia Tolars – SIT"),
("ZAR", "South Africa Rand – ZAR"),
("KRW", "South Korea Won – KRW"),
("ESP", "Spain Pesetas – ESP"), 
 
("SDD", "Sudan Dinars – SDD"),
("SEK", "Sweden Kronor – SEK"),
("CHF", "Switzerland Francs – CHF"),
("TWD", "Taiwan New Dollars – TWD"),
("THB", "Thailand Baht – THB"),
("TTD", "Trinidad and Tobago Dollars – TTD"),
 
("TND", "Tunisia Dinars – TND"),
("TRY", "Turkey New Lira – TRY"),
("AED", "United Arab Emirates Dirhams – AED"),
("GBP", "United Kingdom Pounds – GBP"),
("USD", "United States Dollars – USD"),
("VEB", "Venezuela Bolivares – VEB"),
 
("VND", "Vietnam Dong – VND"),
("ZMK", "Zambia Kwacha – ZMK"),
)