# Generated by Django 4.1.10 on 2024-12-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paybillUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('check', 'Check'), ('Wire Transfer', 'Wire Transfer')], max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.PositiveIntegerField(verbose_name='zip code')),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paybills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('txnType', models.CharField(default='Debit', editable=False, max_length=10)),
                ('amount', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
                ('action', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('Successful', 'Successful')], default='Successful', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.paybilluser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='loginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('browser_type', models.CharField(max_length=100)),
                ('browser_version', models.CharField(max_length=100)),
                ('os_type', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_check', models.ImageField(blank=True, null=True, upload_to='checkfront/')),
                ('back_check', models.ImageField(blank=True, null=True, upload_to='checkback/')),
                ('amount', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='cardholder name')),
                ('card_number', models.IntegerField(verbose_name='card number')),
                ('cvv', models.IntegerField(verbose_name='card cvv')),
                ('expiry_month', models.CharField(blank=True, max_length=30, verbose_name='card expiry month')),
                ('expiry_year', models.CharField(blank=True, max_length=30, verbose_name='card expiry year')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
