# Generated by Django 3.2.23 on 2024-11-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybills',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('Successful', 'Successful')], default='Successful', max_length=50),
        ),
    ]
