# Generated by Django 4.1.10 on 2024-12-05 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True)),
                ('profile_pic', models.FileField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationClients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.DateTimeField(default=django.utils.timezone.now)),
                ('clients_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venexapp.clients')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('btc_wallet', models.CharField(blank=True, max_length=30)),
                ('ethereum_wallet', models.CharField(blank=True, max_length=30)),
                ('usdt_wallet', models.CharField(blank=True, max_length=30)),
                ('litecoin_wallet', models.CharField(blank=True, max_length=30)),
                ('tron_wallet', models.CharField(blank=True, max_length=30)),
                ('phone_no', models.CharField(blank=True, max_length=25)),
                ('profile_pic', models.FileField(blank=True, upload_to='')),
                ('gender', models.CharField(blank=True, max_length=225)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
